## copying the repo

- name: copying the {{COMPONENT}} repo
  ansible.builtin.copy :
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

# installing the redis
- name: Install {{COMPONENT}}
  ansible.builtin.package:  
    name: redis-6.2.11             
    state: present

- name: updating {{COMPONENT}} Listining config
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'



## starting the service

- name: Starting {{COMPONENT}}
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes