
# copying the repo
- name: copying the mongodb repo
  ansible.builtin.copy :
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

# installing the mongodb
- name: Install mongodb
  ansible.builtin.package:  
    name: mongodb-org             
    state: present

# editing the mongod.conf file 
# search and replace "ansible.builtin.replace:"
- name: updating Mongodb Listining config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

# starting mongodb service ## databases hould be started gracfully should avid restart


- name: Enabling and starting Mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes   

# downloading and extracting the schema

# download and extect module "unarchive module "
# module will be called from common role .as its a repetative task

- name: Downloading and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: github-dwld

# Loading the mongodb schema "community.mongodb.mongodb_shell"

- name: Loading catalogue and users schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users