- name: Play1
  hosts: all
  vars:
    URL: google.com   # gloabl/play level variable can be use in any tasks
  tasks:
   - name: Print URL var
     ansible.builtin.debug:
       msg: The value of URL is {{ URL }}

   - name: Print URL var
     ansible.builtin.debug:
       msg: The value of URL is {{ URL }}
     vars:
       URL: yahoo.com  ## local variables

   - name: Print URL var
     ansible.builtin.debug:
       msg: The value of CLI_URL is {{ CLI_URL }}  # runtime varibles / command line




  # Local variables have higher precidence than gloabl
