- name: Play1
  hosts: all
  vars:
    URL: google.com   # gloabl/play level variable can be use in any tasks
  vars_prompt:
    - name: URL
      prompt: Enter the URL    # Prompt varible will have higher precidence than gloabl
      private: no        # will show what we are entering on the screen if no
      
  tasks:
   - name: Print URL var
     ansible.builtin.debug:
       msg: The value of URL is {{ URL }}

   - name: Print URL var
     ansible.builtin.debug:
       msg: The value of URL is {{ URL }}
     vars:
       URL: yahoo.com  ## local variables

   - name: Print URL var
     ansible.builtin.debug:
       msg: The value of CLI_URL is {{ CLI_URL }}  # runtime varibles / command line




  # command line >Local variables >prompt varibale> gloabl
  #runtime varibles / command line -e CLI_URL=var
  # command line varibles will have the highest precidence -e URL=var will overide glabla aswell
  # as local 


