# shell module : specific to version of linux , should not use 

- name: Play1
  hosts: all
  tasks:
   - name: Run shell command
     shell: uptime
     register: OUT  # to show the output of the command , by default it wont show the output after execution

   - name: Print the output of uptime
     ansible.builtin.debug:
       msg: {{ OUT.stdout }} # to get specific output only .stout