- name: Playbook to setup roboshop proj
  #hosts: "{{ COMPONENT }}"  ## for ansible push
  hosts: localhost    ## for ansible pull 
  become: yes    # to run as root user
  roles:
    - "{{ COMPONENT }}"

