- name:  Configuring Yum repo for {{COMPONENT}}
  ansible.builtin.shell: curl -s {{RABBITMQ_URL}} | sudo bash

- name: Install {{COMPONENT}}
  ansible.builtin.package:  
    name: 
     - rabbitmq-server
     - "{{ERLANG_URL}}"           
    state: present

- name: Starting {{COMPONENT}}
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    daemon_reload: yes
    enabled: yes


# adding user and giving permision in rabbitmq

- name: creating user and giving permision {{COMPONENT}}
  community.rabbitmq.rabbitmq_user:
    user: "{{APP_USER}}"
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present