# copying the repo
- name: copying the {{COMPONENT}} repo
  ansible.builtin.copy :
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

# installing the sql
- name: Install {{COMPONENT}}
  ansible.builtin.package:  
    name: 
      - mysql-community-server
      - MySQL-python            
    state: present
## installing MYsl-python to use it foe db password check "community.mysql.mysql_info"

- name: Enabling and starting {{COMPONENT}}
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes


- name: checking the DB Password
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_stat

- name: Rest password block
  when: mysql_stat.failed
  block:
    - name: Resetting the DB Password
      ansible.builtin.shell: grep "temporary password" /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD


    