# instalong nodejs and other setps are writien in nodejs.yml file under comman and 
# it is been called here 

- name: Configuring nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

## cleaning up of the old files 

- name: Cleanup of {{COMPONENT}}
  ansible.builtin.file:
    path: /home/{{APP_USER}}/{{COMPONENT}}
    state: absent # deleting old files

- name: copy {{COMPONENT}} content to {{APP_USER}} home directory
  ansible.builtin.copy :
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APP_USER}}/{{COMPONENT}}
    remote_src: yes
  become_user: "{{APP_USER}"   ## will run as roboshop user else will run as root as we have set the whole playbook to run as root
  