# instalong nodejs and other setps are writien in nodejs.yml file under comman and 
# it is been called here 

- name: Configuring nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs