
# download and extect module "unarchive module "
- name: Download and extract {{COMPONENT}} repo
  ansible.builtin.unarchive:
    src: "{{REPO_URL}}"
    dest: /tmp
    remote_src: yes # will be yes if the remote source is not in ansible server