- name: Configuring YUM repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

- name: installing {{COMPONENT}}
  ansible.builtin.package:
    name:
      - nodejs
      - gcc-c++
    state: present


## create user
# module will be called from common role .as its a repetative task

- name: Create user {{APP_USER}}
  ansible.builtin.include_role:
    name: common ## role /folder file location 
    tasks_from: createuser ## file name

- name: Download DocDB Pem File 
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /home/roboshop/
    mode: '0440'
    owner: roboshop 
    group: roboshop 

  

# module will be called from common role .as its a repetative task

- name: Downloading and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download


# calling cleanup.yml

- name: cleanup of  {{COMPONENT}}, moving  and changing the permisions
  ansible.builtin.include_role:
    name: common
    tasks_from: cleanup

  ## npm install

- name: npm install  based on package.json.
  community.general.npm:
    path: /home/{{APP_USER}}/{{COMPONENT}}/



- name: configuring and starting  {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd