# copying the repo
- name: copying systemd file for {{COMPONENT}}
  ansible.builtin.template :
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Doing a systemctl daemon_reload
  ansible.builtin.shell:
    cmd: systemctl daemon-reload 

    
# starting and enabling the service 
- name: Starting {{COMPONENT}}
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: restarted
    daemon_reload: yes
    enabled: yes
